### ISSUE TITLE
Split Italian and German dynasties

### ISSUE THREAD

**Issue by Methaneus** [ck2plus/CK2Plus#104]
**Italian**
- [x] Transfer all Italian dynasties into their originating region's culture
- [x] Make sure all Italian dynasties have a counterpart in the original Italian (italian) culture

**German**
- [ ] Transfer all German dynasties into their originating region's culture
- [ ] Transfer all German dynasties into the High German (imperial_german) culture
- [ ] Make sure all German dynasties have a counterpart in the original German (german, Alemannic) culture

**Comment by schwarherz** [comment]
Since this hasn't been updated since March 2018 I'm going to assume it is done. Closing.
