### ISSUE TITLE
Succession Laws reverting over time

### ISSUE THREAD

**Issue by schwarherz** [ck2plus/CK2Plus#125]
Per players, succession laws are reverting to defaults after a certain time frame

**Comment by DallanInvictus** [comment]
Could we clarify with the testers if this means ALL succession laws are reverting to Primo, or just the new ones introduced in HF (Eldership/Princely Elective/Imperial Elective)? I THINK I know what might be causing this (probably a maintenance event gone rogue) but clearing that up would help narrow it down.

**Comment by schwarherz** [comment]
That's probably what it is. There's a report in the forums now about laws reverting to gavelkind in 769 as well.

https://forum.paradoxplaza.com/forum/index.php?threads/ck2plus-bug-reports.1164659/#post-25321985

**Comment by MightNight** [comment]
Princely and Imperial Elective have been patched.  The Eldership does not appear in any lawset afaik (I checked the Baltic religion guys, but could not find the option to switch to Eldership.  Once that gets added, we would need to update it for that Succession Law also.

**Comment by DallanInvictus** [comment]
Eldership branches off the succ_institute_tanistry decision like Princely and Imperial elective branch off the succ_institute_feudal_elective decision. I've updated it to add it.

If Baltic doesn't have Eldership already and doesn't have the option to switch to Eldership (or even have a stray law option with a localisation bug) then that is another problem.

**Comment by MightNight** [comment]
Interesting.  Yeah so we have a report that it is apparently happening in the pre-HF succesion laws also.

```I had a bug with succession laws : changed it from agnatic gavelking to agnatic ultimogeniture. Seemed fine at first but a few days/weeks later the law succession law went back to agnatic gavelkind. (with a zoroastrian duke)

Edit : Forgot one thing, I was doing a test run with the beta for patch 3.1. ```

If we get one more report regarding that I'll just reopen the issue

**Comment by schwarherz** [comment]
Edited description per new info

**Comment by MightNight** [comment]
Ok, so it seems like now it only reverts to Gavelkind after passing a succession law.  I have no idea how and why we need these scripts, so I let you guys handle them.

**Comment by schwarherz** [comment]
@DallanInvictus Do you mind if I assign this to you?

**Comment by DallanInvictus** [comment]
No problem,, it's almost certainly my fault anyway.

**Comment by schwarherz** [comment]
Closing as this seems to have been fixed. Re-open if reoccurs.
