### ISSUE TITLE
Can't make some desicions on CK2Plus 5.0 Alpha 1.1

### ISSUE THREAD

**Issue by Mental-Reservation** [ck2plus/CK2Plus#198]
A lot of things like hunt, pilgrimage, hajj, etc can't be done. In case of hunt, I guess it because of string:
is_not_in_regency_trigger = no
instead of
is_not_in_regency_trigger = yes
Check this screens:
![Снимок2](https://user-images.githubusercontent.com/51900899/124894045-d0899f00-dfca-11eb-95bd-183adc9b64c2.PNG)
![Снимок3](https://user-images.githubusercontent.com/51900899/124894070-d67f8000-dfca-11eb-99d9-4c1f631666e0.PNG)
![Снимок4](https://user-images.githubusercontent.com/51900899/124894083-da130700-dfca-11eb-922a-02f917a90aad.PNG)

**Comment by Whizzer** [comment]
You're right about the cause. Thanks for letting us know! Fix incoming.
