### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by Mental-Reservation** [ck2plus/CK2Plus#200]
1) If ruler gains a syptome or a disease, court physician don't want to heal. The "Ask court physician for treatment" (or smt like that) doesn't works too
2) Can't join benedectine order if starts in 1000 A.D, the order don't have any member
3) "Plan a feast" decision gives you a money instead of taking. After that, it's just not working. No feast in a kingdom :(

**Comment by Mental-Reservation** [comment]
Oh, and if you increase crown authority, it's decrease relation with all courts and vassals, but it's illogical, ordinary courtiers should not be worse about crown authority

**Comment by schwarherz** [comment]
Thank you for your reports. These have been fixed on dev. In the future, please report issues individually so that we can track them easier, thank you.

Closing issue.
