### ISSUE TITLE
Iceland is a Theocracy in 867 start date (5.0 Alpha 1.3)

### ISSUE THREAD

**Issue by Doomathon** [ck2plus/CK2Plus#203]
All four counties in Iceland are theocracy government (and therefore un-playable) in the 867 start.

Using version 5.0 Alpha 1.3

Reproduction steps:

1. Start a new game from the main menu
2. Choose the 867 start date
3. Observe that Iceland is ruled by two theocracies, and neither are playable

**Comment by Whizzer** [comment]
Looks like we missed something after all. Thanks, fix incoming shortly.
