### ISSUE TITLE
Holy war CB available to unreformed germanic pagan Saxony, increasing noreligion's moral authority.

### ISSUE THREAD

**Issue by Festerdam** [ck2plus/CK2Plus#206]
What's wrong: Moral authority of `noreligion` can be changed, pagan can declare holy wars before reformed and before crusades.
Have holy fury, old gods and other DLCs installed.
Checksum NPSX.
![Captura de ecrã de 2021-08-06 15-38-00](https://user-images.githubusercontent.com/24637623/128529779-598c451a-0a96-4472-8923-505ce2344b74.png)

(Also, unrelated to the issue, is Saxony supposed to be anglosaxon instead of saxon?)

**Comment by schwarherz** [comment]
I believe the holy wars are WAD for plus, I'll double check the code and any documentation at some point to confirm. The anglo-Saxon issue is likely a just a localization change that we haven't ported from Cleanslate yet

**Comment by Festerdam** [comment]
Does WAD mean «without a doubt» in your message?

**Comment by schwarherz** [comment]
Working as designed

**Comment by Festerdam** [comment]
Is the `noreligion` in the CB description expected?

**Comment by schwarherz** [comment]
I missed that part. That's definitely not right. We'll have to look further into it
