### ISSUE TITLE
Choice effects of number of shouts at the Mecca stone event inverted; only no effect can occur from selection.

### ISSUE THREAD

**Issue by Festerdam** [ck2plus/CK2Plus#209]
![Captura de ecrã de 2021-08-08 16-50-18](https://user-images.githubusercontent.com/24637623/128638052-f6d1471d-633e-46a7-9abb-61b211ea4846.png)
![Captura de ecrã de 2021-08-08 16-50-23](https://user-images.githubusercontent.com/24637623/128638063-dc156902-8d01-418d-a3e0-f2794cb9d1bb.png)
Character should become humble if shouting on every circuit, for it demonstrates humility towards God and not pride as suggested by the event.
Also, I think the four effects of `No Effect` should be omitted because 4 * 25% = 100%.

**Comment by artemgur** [comment]
If I recall correctly the effects of the event are vanilla. Don't know how it should be, just informing
