### ISSUE TITLE
Sickness event broke. Physician does not treat characters

### ISSUE THREAD

**Issue by dashiedash** [ck2plus/CK2Plus#210]
![image](https://user-images.githubusercontent.com/31542077/129842466-f4102673-4d2e-42ea-81f2-bc05f3a436e1.png)

Hello friends.

As seen in this image, this event in particular is quite broken compared to the vanilla version of the event. The choice "I must find a court physician!" appears even though I already have a court physician. And when I tried to summon my court physician, the physician does not treat the character at all. It would be nice to find a fix for this.

**Comment by Whizzer** [comment]
Try as I might, I cannot reproduce this. How often does the event malfunction? Are you using CleanSlate as well? Using any other mods? What is your checksum?

**Comment by dashiedash** [comment]
> How often does the event malfunction?

It malfunctions every time it fires.

> Are you using CleanSlate as well?

Yes.

> Using any other mods?

CK2+ and CleanSlate are the only mods I have that does major changes to the game in general. The rest are simply minor changes (Claim All De Jure Titles, Legacy of Rome Expanded, Vassal Call To Arms) and/or graphical changes (Patrum Scuta for CK+, Immersive Religious Holdings, Better Italian & Roman Portraits, Better Greek Portraits, etc.) which I don't believe would affect the event in question at all.

> What is your checksum?

SOHY, from what I see in the launcher.

**Comment by dashiedash** [comment]
Here's a little update on the issue on my side. I deleted the two mods CK2+ and Clean Slate and re-subscribed to them. I waited for the event to run again. The option "Call for my Court Physician at once!" disappeared. Note that I already appointed a Court Physician.
![image](https://user-images.githubusercontent.com/31542077/130320184-cd634e69-1781-49cd-ba89-34aca449b64a.png)

**Comment by HovaSS111** [comment]
i have the same problem with ck2 + and sleaсstate mods,if i off ck2+ this problem disappears
