### ISSUE TITLE
Africa ravaged by Plague...even though the Plague has not come yet.

### ISSUE THREAD

**Issue by dashiedash** [ck2plus/CK2Plus#211]
![image](https://user-images.githubusercontent.com/31542077/130342120-ae515d07-082c-4831-b6cf-6f13f2425c2a.png)
Hello again, friends.

Another bug that I keep on encountering every time I start a new game is the notification that the entire African continent has been smacked by the Plague, which I assume that it refers to the Black Death. When I check the diseases map mode, the only plague I last saw was Consumption ravaging that tiny portion of Nubia. This happens around a year has passed in-game.

**Comment by Whizzer** [comment]
The fix for this issue has not yet made it to a release, but it's been taken care of.
