### ISSUE TITLE
Seljuk is landless at the "A New Millenium" start

### ISSUE THREAD

**Issue by Grandaxin** [ck2plus/CK2Plus#213]
So title speaks for himself
Seljuk is landless, so as half Iran region
My cache is clear, i only lauch CK2+ and Cleanslate with my game
![seljuk](https://user-images.githubusercontent.com/75272137/133748890-b8a62024-daad-4381-93db-962e2eda35b7.jpg)
![image](https://user-images.githubusercontent.com/75272137/133749106-51611f99-0633-430a-ba86-ed9f2d9f01ee.png)

**Comment by Whizzer** [comment]
The Millennium bookmark is actually not supported right now. Reverting to the vanilla map meant temporarily losing all title history that was a part of this bookmark. It will be brought back later, but for the next update, the bookmark will be removed.
