### ISSUE TITLE
Monks and Mysteries bugged/Also no secret societies?

### ISSUE THREAD

**Issue by Cybozoa** [ck2plus/CK2Plus#214]
Hi, hopefully I am doing this correctly. I've got two things that I suspect are bugs, firstly as seen below the proclaim secret faith warns about no (monks and mysteries) DLC. Secondly it seems like I am unable to create a secret society for pagans? (Tried germanic, celtic, slavic, and tengri.) 
My game:
SOHY, 3.3.5. and Cleanslate, CK2plus, Improved genetics 2.0 Cleanslate, trait softcap exterminated. 

![20210917104043_1](https://user-images.githubusercontent.com/90898997/133753646-a7a1d899-98a9-41d2-ad62-5d3524ff542f.jpg)

**Comment by Whizzer** [comment]
Thanks, should be fixed now.

**Comment by Whizzer** [comment]
Regarding your second question: secret religious societies are disabled in CK2+. You can do just about everything without requiring such a society.
