### ISSUE TITLE
SEIZE TRADE POST CB

### ISSUE THREAD

**Issue by ElwinSP** [ck2plus/CK2Plus#216]
Hi, i ahve juststarted with 5.0, playing as venice. When declaring war to a small independt duchy (in dalmatian coast) in order to seize their trade post (owned by their own feudal regime) the war automatically stops due to CB no longer being valid although the trade post is still there.

**Comment by ElwinSP** [comment]
So, strangely enough the bud does not reproduce when i declare war on kingdoms, just on duchies. 
But when i declare on war on kingdoms and empires u get a different bug. After winning th war (btw nice addition that conquering a trade post does not initially destroy it) the trade post is removed. But i cannot build a new one because it says still a merchant republic controls the trade post (which is non-existant). I guess in cleanslate you tried to code in trade post not getting destroyed on conquer which is great but still after winning the war there must have abeen an old part of code which makes the trade post dissapear. I was not able to build a new one and the situation stayed the same for a couple of years when i saw the feudal owner of the province had built a new tradepost.

**Comment by Whizzer** [comment]
I cannot reproduce any of these issues. CleanSlate does not, to my knowledge, do anything with tradeposts, due to that all being hardcoded. If you can provide savegames, that would be most appreciated.
