### ISSUE TITLE
Several bugs found during my HRE playthrough

### ISSUE THREAD

**Issue by lhr001fly** [ck2plus/CK2Plus#217]
1. When I grant a vassal mayor a duke title to make him a merchant republic, my current heir is excluded from inheritance.
2. Claim the Papcy CB always ends inconclusively shortly after I declare the war. Also the antipope is disposed. 
3. The vassals who gains title from me follow agnatic elective succession law. I don't know if it's a bug or it is designed so.

**Comment by Whizzer** [comment]
Thanks for providing these reports. Unfortunately, I can't reproduce any of these issues. That may mean they've already been solved. Can you provide steps to reproduce them, and/or savegames?
