### ISSUE TITLE
Cant get claim from pope even with positive acceptance score.

### ISSUE THREAD

**Issue by Lopatouovalil** [ck2plus/CK2Plus#221]
pope will not accept.

**Comment by Whizzer** [comment]
While we can mod how this diplomatic interaction is scored, I doubt we can fix this bug. Perhaps with a save game and/or steps to reproduce this issue.

**Comment by schwarherz** [comment]
Issue is over a year old with no further reports and no provided resources to reproduce the issue. Closing.
