### ISSUE TITLE
You can demand tribute from your own vassals and foregin vassals which border you

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#225]
I use the version from Steam, released at 6th December.

Steps to reproduce:
Start as, for example, the Eastern Roman Emperor at 769
Right click any of your vassals (or vassals of your vassals)
Or right click any foreign vassal which borders you
Option "Demand Tribute" appears

**Comment by Whizzer** [comment]
This one is already fixed. Next update is due very soon - perhaps tonight.
