### ISSUE TITLE
Imperial Decadence popup without any number

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#227]
![image](https://user-images.githubusercontent.com/59292863/147243661-de962562-b78f-421d-97df-42544ca8f6e0.png)

I use the version released today (or yesterday, depending on the time zone)

Steps to reproduce:
Start as Latin Empire on the Latin Empire bookmark
Wait a few days
The Imperial Decadence popup will appear without any number

**Comment by schwarherz** [comment]
Verified on my end. Ruler does not always show correctly either. Imperial Decadence may need a full rework.

**Comment by schwarherz** [comment]
Per above commit, assuming issue fixed. Closing.
