### ISSUE TITLE
Infidel Tax modifier string bug

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#229]
![image](https://user-images.githubusercontent.com/59292863/147289775-18646b9b-fe20-4a24-b291-2bdde6683262.png)

The tooltip has that text (with both adjectives - Christian) for all non-Muslim provinces held by Muslim rulers (for example, on 769 bookmark both Paulican Karin and Tengri Balanjar have this tooltip)

**Comment by schwarherz** [comment]
File with this localization in it is not present in Plus. This is a CleanSlate issue and appears to have been solved, closing.
