### ISSUE TITLE
Basic Paddock in cities can't be upgraded

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#231]
![image](https://user-images.githubusercontent.com/59292863/147371148-18b6a2af-fe12-47fb-8090-afcaa6d2c352.png)

The Basic Paddock building is marked as a final tier, Next tiers exist in the mod files, but are unbuildable.

To see it in game, start the game at 1066 bookmark and click on any city.

**Comment by Saeveo** [comment]
@artemgur It's being caused by the special camel stables for desert cities, I think. In common/buildings/00_CK2Plus_city.txt, the following buildings:

ct_desert_stable_2 
ct_desert_stable_3 
ct_desert_stable_4 
ct_desert_stable_5 

need to have:

```
potential = {
    terrain = desert
}
```
