### ISSUE TITLE
Byzantine kingdom creation/crown laws

### ISSUE THREAD

**Issue by Bismarckingit** [ck2plus/CK2Plus#233]
The eastern Roman imperial provinces cant seem to be created after being organized, leaving them functionally worthless. Additionally, crown authority can never effectively be raised above medium, thusly it can never get the reforms necessary to actually egin creating them.

**Comment by Whizzer** [comment]
I can organise and create Phrygia without issues and raise crown authority to high, so I need more details if you want me to help you. What start date, what's keeping you from 'effectively' raising crown authority, what's keeping you from creating these provinces?

**Comment by Bismarckingit** [comment]
Im able to do the organize decisions, but I cant seem to create any of the titles. I also can't raise crown authority due to Byzantine succession changing it, effectively preventing any move to a higher crown authority than high, as even a strong basileus is set to medium. I tested this using commands, and I cant create the kingdom titles, even if I have the creation of kingdoms unrestricted. I downloaded this mod only a couple days ago, too.

**Comment by Bismarckingit** [comment]
*One potential problem might be that I had this mod before, and deleted it before installing this one. Maybe its a problem with the cache?

**Comment by Bismarckingit** [comment]
Okay, Ive checked the problem

I can form the provinces, but I cant create them without instituting a law that allows to create kingdoms

![20220102_112640](https://user-images.githubusercontent.com/50720330/147882346-97c3b3a2-bff2-468c-8b7d-18636675c9dc.jpg)


The problem is, its impossible to get the laws necessary because of how crown laws work

I am running Cleanslate as well, but it seems to be the only way to even allow this mod to work

**Comment by Bismarckingit** [comment]
If I had to guess, either law changes or government changes screwed something up, as I can see the requirement of "allowed to create kingdoms" in the files for these provinces, so if I had to guess, either that requirement was added or some method of bypassing it was removed on accident. 

(On an unrelated note, factions seem to be perpetually content, I dont know what's up with that)

**Comment by Whizzer** [comment]
Deleting old versions is part of installing mods properly, unless otherwise specified. 
Lowered crown authority by succession should be restored by getting coronated as a Strong Basileus, if I recall correctly.
CleanSlate is indeed required, by design.

Factions are a different matter, so if you are very certain there's something wrong there, please open a new issue.
