### ISSUE TITLE
3 years hanging conspiracy at 500%

### ISSUE THREAD

**Issue by HovaSS111** [ck2plus/CK2Plus#236]
![image](https://user-images.githubusercontent.com/84979897/150335010-5d61716a-6e13-4b2e-8687-d0d472b0d9f2.png) 

does the betrayal contract work?

**Comment by Saeveo** [comment]
@HovaSS111 In event\CK2_plot_events.txt, go to event Plus.205. Change
```
plot_target_char = {
	NOT = { vassal_of = ROOT }
}
```
to
		
```
plot_target_char = {
	vassal_of = ROOT
}
```
