### ISSUE TITLE
Bugs related to renaming internal identifiers for cultures in Melting Pot events

### ISSUE THREAD

**Issue by Doomathon** [ck2plus/CK2Plus#247]
Specific file in question: CK2Plus_melting_pot_events.txt

The English, Anglo-Norse, and Norman melting pot events weren't updated for proper CleanSlate compatibility when the internal identifiers for the Anglo-Saxon and French cultures were changed from the vanilla ones.

Consequently, it is only possible to get English or Anglo-Norse to appear in provinces of Saxon (as in Saxony, in Germany) culture in England, which is a mildly unlikely scenario to occur. It's also impossible to trigger the English melting pot as French culture, as the events are looking for the Frankish culture instead.

For similar reasons, it's also surprisingly difficult to trigger the Norman melting pot, as the most likely culture one would think to trigger it with (Norse ruler ruling over French provinces) doesn't work because the events are looking for Frankish provinces. The Norman melting pot DOES trigger properly for Norse rulers in Breton or Occitan land, however.

**Comment by schwarherz** [comment]
Verified this has since been fixed. Closing.
