### ISSUE TITLE
When you send a character to China as a eunuch, they don't leave your court

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#250]
When you send a character as a eunuch to China, they become a eunuch, but stay at your court and don't leave to China.

It seems that at least in some cases the same happens when you send a concubine to China.

**Comment by schwarherz** [comment]
I don't see a reason why this would happen. Someone being "sent to china" just kills them as far as the engine sees. I see the issue is several months old, can you confirm it's still happening? If I don't get a response I will close the issue

**Comment by schwarherz** [comment]
Closing per previous comment.
