### ISSUE TITLE
Sunni characters very rarely choose Sunni Mu'thazilite/Ash'ari schools

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#251]
Very few characters in the world have Mu'thazilite and Ash'ari traits, despite the decisions to get these traits have very easy conditions (only requires 50 piety).

For example, when I checked that about 30 years after 769 bookmark, my character was the only Ash'ari in the world.

It's a vanilla issue caused by very low ai_will_do and very high ai_check_interval of these decisions. For my personal use I increased ai_will_do and decreased ai_check_interval of them, and if that works well, I will create a pull request.

**Comment by schwarherz** [comment]
If this is a vanilla issue, this may be more suited for CleanSlate. Closing issue for now
