### ISSUE TITLE
AI very rarely goes to Hajj. And unnecessary do_not_disturb flag when starting Hajj

### ISSUE THREAD

**Issue by artemgur** [ck2plus/CK2Plus#252]
AI goes to Hajj too rarely. When I checked that 33 years after 769 bookmark, only 3 characters in the world had been to Hajj (and one of them is player character, and the remaining two are court physicans with physician_well_traveled_pilgrim flag and [simply spawned](https://github.com/ck2plus/CK2Plus/blob/main/CK2Plus/events/rip_physician_events.txt) with the Hajajj trait). It is caused by very low ai_will_do and weird AI trigger (AI can only go to Hajj if the character is not younger than 30, has no less than 10 scaled wealth, not cynical, slothul, proud, deceitful, decadent).

Also the decision go_on_hajj [sets](https://github.com/ck2plus/CK2Plus/blob/main/CK2Plus/decisions/minor_decisions.txt) do_not_disturb flag which is [never removed](https://github.com/ck2plus/CK2Plus/blob/main/CK2Plus/events/soi_on_hajj.txt). Because of that, character who have been to Hajj, are busy for the rest of their lives.

**Comment by schwarherz** [comment]
I believe this may have been fixed. I would appreciate research to verify. I will close if no further activity in 90 days
