### ISSUE TITLE
Court Physician never triggers.

### ISSUE THREAD

**Issue by Czechys** [ck2plus/CK2Plus#254]
![Snímek obrazovky 2022-10-11 162916](https://user-images.githubusercontent.com/88946285/195124908-e4af688a-535c-4fee-b820-2f01f5df132a.png)
Doesn´t do anything.

No Mods other than CleanSlate and CK2+

**Comment by Czechys** [comment]
When i triggered any of the physician events by console: instead of vanilla behaviour of replacing the court physician with yourself in the event. The place where a name would be simply remained empty.

Vanilla behaviour
![Snímek obrazovky 2022-10-11 170742](https://user-images.githubusercontent.com/88946285/195129470-0af2aba5-b6b6-46ee-acc0-586e82265d07.png)
CKPlus behaviour
![Snímek obrazovky 2022-10-11 170908](https://user-images.githubusercontent.com/88946285/195129755-22ca157e-6e0e-4899-80a9-cc9f5202d8c4.png)

**Comment by GsGuerreiro98** [comment]
Having the exact same problem here.

**Comment by schwarherz** [comment]
Which version of the mod are you using? Steam or GitHub? We have been unable to reproduce this bug on our end.

**Comment by GsGuerreiro98** [comment]
I’ve been using the Steam version. Should I download the GitHub one?

**Comment by Czechys** [comment]
When I opened this issue I was able to reproduce this on both the steam version and on the Github one.

**Comment by Whizzer** [comment]
Can you also reproduce it on a new game without any other mods in play other than CleanSlate and CK2+? Note that CleanSlate is absolutely required for CK2+. Playing without it will cause this bug.

**Comment by Czechys** [comment]
Yes. When I opened this issue I was able to reproduce this on a new game. Both on the steam version and on the Github version of CK2+. I had no other mods active other than CK2+ and CleanSlate.

**Comment by Whizzer** [comment]
Please upload a savegame, so that I can try to fix it.

**Comment by Czechys** [comment]
I was not able to recreate this issue after a fresh download of both CleanSlate and CK2+ from Steam Workshop. 
I was not able to recreate this issue after a fresh download of both CleanSlate and CK2+ from Github. 
I was able to recreate this issue with my old files. Which have a wrong checksum.

**Comment by GsGuerreiro98** [comment]
> Please upload a savegame, so that I can try to fix it.

How do I upload an save game here on GitHub? I have one with this problem and would be very grateful of there was a way to fix it and continue playing in it haha

**Comment by Whizzer** [comment]
> > Please upload a savegame, so that I can try to fix it.
> 
> How do I upload an save game here on GitHub? I have one with this problem and would be very grateful of there was a way to fix it and continue playing in it haha

You can't. Feel free to upload it elsewhere and put a link here, or contact me on the CK2 forums/CK2+ Discord.

**Comment by CBornholdt** [comment]
This was happening to me as well during my most recent CK2Plus game. After some troubleshooting in the various events, I discovered a solution which implies some deeper problems; using 'reloadevents' in the console upon starting/loading a game seems to resolve the issue.

I am using Linux (Ubuntu 22.04), and have seen this behavior with 3.3.3, 3.3.4, and 3.3.5 using only cleanslate and ck2plus.

**Comment by schwarherz** [comment]
No recent reports of this issue. Discussion indicates that issue may have been resolved. Closing issue pending recurrence. If issue is reopened please provide save game for testing purposes and verify checksum is correct prior to opening.
