### ISSUE TITLE
Rollo related event bug: Rollo fails to convert his capital province to Norman

### ISSUE THREAD

**Issue by Doomathon** [ck2plus/CK2Plus#255]
Relevent file: events/CK2Plus_norman_events.txt

Specifically, in event Plus.2753, if Rollo chooses to convert to Christianity by event, his capital is supposed to convert from French culture to Norman, but the event checks for Frankish culture in his capital, so it never occurs

**Comment by Whizzer** [comment]
Fixed, along with several others. Thanks for pointing it out!
