### ISSUE TITLE
Broken Dynasty Trees

### ISSUE THREAD

**Issue by Foulyn** [ck2plus/CK2Plus#257]
In the last six months that I've been playing CK2Plus, I've noticed quite a few dynasties where the dynasty tree doesn't display correctly. I'm attaching an archive with screenshots of broken dynasties, which were easy to find.
I am attaching a link to the archive with screenshots.
https://drive.google.com/file/d/1-sikEkVNiMaoCkY_KSHJtB3zfgdLlh7H/view?usp=share_link

**Comment by schwarherz** [comment]
Upon searching several of the characters referenced in the screenshots, it appears that this has been fixed. Closing pending further report.
