### ISSUE TITLE
The Byzantine Emperor wont be coronated

### ISSUE THREAD

**Issue by Bismarckingit** [ck2plus/CK2Plus#267]
For some reason in recent playthroughs of mine I have noticed that the Byzantine empire coronation event simply will not fire. I have deleted my cache from the mod, and I have the most current version of both this mod and CleanSlate. I will pay into the patriarch setting up the coronation, the coronation will be agreed to, then the event for being coronated will simply never fire at all.

**Comment by schwarherz** [comment]
Per the research done in Discord: Issue appears to stem from the Ecumenical Patriarch position being vacant in some start dates.
