### ISSUE TITLE
Invasion CB is unavailable

### ISSUE THREAD

**Issue by yetanotherqubick** [ck2plus/CK2Plus#289]
I don't know if this is intended or not, but you can't use Invasion casus belli. E. g., if your character is the Child of Destiny or has the Blood of Alexander the Great. Pretty annoying, since you can't conquer any kingdom until Crusades.

**Comment by schwarherz** [comment]
I just checked the invasion cb. I'm not seeing it disabled at all. I'm going to need more info on potential other mods etc. Closing issue pending update.
