### ISSUE TITLE
Rework Gavelkind succession

### ISSUE THREAD

**Issue by vukivan** [ck2plus/CK2Plus#32]
This includes investing for the best implementation possible. Currently we cannot change succession localisation, but appart from that everything else is fairly straightforward.

- [ ] Gavelkind:
- New law group will be added to crown laws titled: "Additional Inheritance Law" - AIL
- Primary succession laws will have their localisation updated to inform the player about the used AIL.
- Default value for AIL is "None" - Other option is "Gavelkind"
- Gavelkind succession law will be disabled permanently
- Elective Gavelkind succession law will be disabled permanently
- Titles with gavelkind will be switched to primogeniture and their AIL will be set  to "Gavelkind"
- Gavelkind faction will be modified to demand AIL law change instead.
- Titles which gave AIL set to "Gavelkind" can switch primary succession law only to "Seniority", "Ultimogentiure" or back to "Primogeniture".
- [ ] Succession under AIL set to "Gavelkind":
- Succession will be implemented as it is for nomads - except for splitting the realm. (Plus.2655)
- Up to four heirs can inherit. Heirs are selected based on current primary succession law.
- Primary heir should get capital, primary title and one county more than other sons.
- If there are more than one titles with the same tier of the primary title they will be given to secondary heirs.
- All county titles given to any heir should be neighbouring each other if it is at all possible.

**Comment by schwarherz** [comment]
Closing due to age.
