### ISSUE TITLE
Rework Elective Succession 

### ISSUE THREAD

**Issue by vukivan** [ck2plus/CK2Plus#33]
- [ ] Succession under AIL set to "Elective":
- Elective succession will be disabled permanently.
- Claimant wars should be made far less frequent on elected/coronated rulers.
- On succession (on_death or abdication) primary heir inherits the title normally acording to primary inheritance law.
- After succession, ruler can call for Election.
- Ruler will no longer be allowed to ask for coronation/papal coronation without being elected.
- Ruler no longer gets uncrowned trait.
- If ruler doesn't call for election for more than 3 months after succesion he gets a penalty trait "Unelected".
- Election procedure - a second candidate must be found in following search order:
    - electors of the same dynasty as ruler (claimants first)
    - electors who are close relatives (claimants first)
    - ruler's adult siblings if they have better stats. (can be unlanded)
    - ruler's dynasty landed members
    - elector who is claimant
    - powerful vassal if claimant
    - random claimant in the realm with good stats
    - random independant claimant outside the realm
    - any elector
    - powerful vassal
    - foreign neighbouring king
    - random vassal with good stats
    - For HRE, second candidate must be of proper religion, german and landed.
    - For ERE, second candidate must be of proper religion.
    - For traditional elective realms (germanic?), culture group should match previous ruler.
- Electors vote based on these priorities:
    - self
    - dynasty
    - relative
    - alliance
    - NAP
    - culture_group
    - opinion (give sitting ruler a bonus +10 or +20)
- If unlanded sibling was elected he/she inherits all the land from emperor. Otherwise whoever is elected gets a new title.
- Electors are by default dukes and kings.
- If there are no dukes in a kingdom, counts become electors.
- Sitting ruler gets one vote automatically (from himself). That is also the tie-breaker.
- If sitting ruler loses election he gets a strong inheritable claim. He shouldn't be allowed to press his claim in a war.
- Once ruler is elected he gets "Elected" trait and can ask for coronation.
- [ ] Confirmation:
- A coronated ruler can ask in advance for his heir to be elected. Same election rules will apply.
- Approved heir will get "Elected" trait and will inherit normally according to primary succession.
- [ ] Electors Law:
- New Crown Law group "Valid Electors Law"-VEL is added if AIL is set to "Elective".
- Default value is "Territorial", other value is "Appointment"
- Territorial means that electors are dukes and kings, or counts if there are no dukes in the kingdom.
- Appointment will select up to 4 most powerful vassals (at least Dukes) as Electors. After that ruler can appoint new electors which have to be approved by other Electors. "Appointment" is only available in imperial realms.
- [ ] Special HRE snowflake stuff:
- HRE gets additional VEL law, "Historic" where electors are stem duchy owners (or grand duchy) prior to 1180:
    d_franconia or k_grand_franconia
    d_luxembourg or k_grand_luxembourg
    d_swabia or k_grand_swabia
    d_eastphalia (if it doesn't exist, then d_westphalia) or k_grand_saxony
    d_bavaria or k_grand_bavaria
    k_brandenburg only if it exists
    k_arch_austria only if it exists
    k_grand_tuscany only if it exists
- Between 1180 and 1257 HRE will use "Territorial" VEL.
For additional consideration:
- We can, on rulers death create a dummy title and use it to remember history. Then destroy that tile, and once election is complete copy title history from the dummy to real empire. This will make it look like "sede vacante" in history.
- Non-elected, non-coronated rulers shouldn't have crowns.

**Comment by schwarherz** [comment]
Closing due to age.
